apiVersion: apps/v1
kind: Deployment

metadata:
  name: postgres
  namespace: opsflow

spec:
  replicas: 1

  strategy:
    type: Recreate

  selector:
    matchLabels:
      app: postgres

  template:

    metadata:
      labels:
        app: postgres

    spec:
      containers:
        - name: postgres

          image: postgres:17-alpine

          ports:
            - containerPort: 5432

          env:

            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: opsflow-config
                  key: DB_NAME

            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: opsflow-config
                  key: DB_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: opsflow-db-secret
                  key: POSTGRES_PASSWORD

          resources:

            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:

            exec:
              command:
                - sh
                - -c
                - pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"

            initialDelaySeconds: 5
            periodSeconds: 5

            timeoutSeconds: 3
            failureThreshold: 5

          livenessProbe:

            exec:
              command:
                - sh
                - -c
                - pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"

            initialDelaySeconds: 15
            periodSeconds: 10

            timeoutSeconds: 3
            failureThreshold: 3

          volumeMounts:

            - name: postgres-data
              mountPath: /var/lib/postgresql/data

            - name: postgres-init
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true

      volumes:

        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc

        - name: postgres-init
          configMap:
            name: postgres-init