replicaCount: 2
serviceAccount:
  create: true
  name: aws-load-balancer-controller
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi
enableShield: false
enableWaf: false
enableWafv2: false
controllerConfig:
  featureGates:
    NLBGatewayAPI: false
    ALBGatewayAPI: false
    GatewayListenerSet: false
